name: CD release

on:
  workflow_run:
    workflows: ["CD build"]
    types:
      - completed
  push:
    branches: [ "main" ]
  # Uncomment for testing only
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Build and package backend
      run: |
        make build
        tar cvzf build.tar.gz build

    - name: Get Next Version
      id: semver
      uses: ietf-tools/semver-action@v1
      with:
        token: ${{ github.token }}
        majorList: release

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: |
          $GITHUB_WORKSPACE/supercluster.zip
          $GITHUB_WORKSPACE/install.sh
        draft: false
        tag: ${{ steps.semver.outputs.next }}
        body: Changelog Contents
        token: ${{ github.token }}
