name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Setup Node.js environment
      uses: actions/setup-node@v3.5.0
      with:
        # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
        node-version: 16.14

    - name: Install frontend dependencies
      run: cd ui && yarn

    - name: Build frontend
      run: cd ui && yarn build

    - name: Clone/Build/Install/Init kubo
      run: |
        cd .. && git clone https://github.com/ipfs/kubo && \
        cd kubo && git checkout 38117db6f && \
        go build  "-trimpath" -ldflags="-X "github.com/ipfs/kubo".CurrentCommit=38117db6f" \
          -o "cmd/ipfs/ipfs" -asmflags=all=-trimpath="" -gcflags=all=-trimpath="" \
          "github.com/ipfs/kubo/cmd/ipfs" && \
        ./cmd/ipfs/ipfs init

    - name: Build plugin
      run: ls .. && ls ../.. && IPFS_VERSION=$(pwd)/../kubo make install

    - name: Test ipfs plugin load
      run: ../kubo/cmd/ipfs/ipfs version

    - name: Test client
      run: go test -v ./...
