name: CI build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Setup Node.js environment
      uses: actions/setup-node@v3.5.0
      with:
        # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
        node-version: 16.14

    - name: Install frontend dependencies
      run: cd ui && yarn

    - name: Build frontend
      run: cd ui && yarn build

    - name: Build backend
      run: make build

    - name: Test client
      run: go test -v ./...

    ## removing this till we upgrade github
    # - name: Archive production artifacts
      # uses: actions/upload-artifact@v3
      # with:
        # name: plugin-artifacts
        # path: |
          # supercluster
          # ui/build
